# Generated by Django 5.2.5 on 2025-08-30 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('esta_ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.CharField(blank=True, default='', max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('capacidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(blank=True, default='', max_length=50)),
                ('marca', models.CharField(blank=True, default='', max_length=50)),
                ('esta_ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['placa'],
                'indexes': [models.Index(fields=['placa'], name='cacambas_ve_placa_deddb1_idx'), models.Index(fields=['numero_interno'], name='cacambas_ve_numero__6b3365_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_entrega', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Entrega (R$)')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade (m³)')),
                ('data_hora_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Saída')),
                ('status', models.CharField(choices=[('A ENTREGAR', 'A entregar'), ('EM ROTA', 'Em rota'), ('CONCLUIDO', 'Concluído'), ('PENDENTE', 'Pendente Cancelamento'), ('CANCELADO', 'Cancelado')], default='A ENTREGAR', max_length=20, verbose_name='Status')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cacambas.produto', verbose_name='Produto')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cacambas.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_hora_saida'],
            },
        ),
    ]
