# Generated by Django 5.2.5 on 2025-08-21 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Produto')),
                ('esta_ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.CharField(max_length=50, unique=True, verbose_name='Número Interno')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('capacidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Capacidade (m³)')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('esta_ativo', models.BooleanField(default=True, verbose_name='Está ativo?')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade (m³)')),
                ('data_hora_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Saída')),
                ('status', models.CharField(choices=[('CONCLUIDO', 'Concluído'), ('PENDENTE', 'Pendente Cancelamento'), ('CANCELADO', 'Cancelado')], default='CONCLUIDO', max_length=20, verbose_name='Status')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cacambas.produto', verbose_name='Produto')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cacambas.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data_hora_saida'],
            },
        ),
    ]
