# Generated by Django 5.2.5 on 2025-09-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacambas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='endereco_entrega',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço de Entrega'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='nome_destinatario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Destinatário'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='telefone_destinatario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Destinatário'),
        ),
    ]
