# Generated by Django 5.2.5 on 2025-08-21 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacambas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data_hora_saida']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['placa']},
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_hora_saida',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cacambas.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(choices=[('CONCLUIDO', 'Concluído'), ('PENDENTE_CANCELAMENTO', 'Pendente de Cancelamento'), ('CANCELADO', 'Cancelado')], default='CONCLUIDO', max_length=30),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cacambas.veiculo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='esta_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='capacidade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='esta_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='numero_interno',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['placa'], name='cacambas_ve_placa_deddb1_idx'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['numero_interno'], name='cacambas_ve_numero__6b3365_idx'),
        ),
    ]
