# Generated by Django 5.2.5 on 2025-08-29 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacambas', '0002_alter_movimentacao_options_alter_produto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data_hora_saida'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_hora_saida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Saída'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cacambas.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade (m³)'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='status',
            field=models.CharField(choices=[('A ENTREGAR', 'A entregar'), ('EM ROTA', 'Em rota'), ('CONCLUIDO', 'Concluído'), ('PENDENTE', 'Pendente Cancelamento'), ('CANCELADO', 'Cancelado')], default='A ENTREGAR', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cacambas.veiculo', verbose_name='Veículo'),
        ),
    ]
