# Generated by Django 5.2.5 on 2025-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacambas', '0002_movimentacao_endereco_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='valor_entrega',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
